"""Phase 10 manuscript-ready audit tables and figures.

This module is deliberately lightweight and standard-library only.  The goal is
for the tables and figures that appear in the manuscript to be regenerated
from proof-audit JSON/CSV payloads, never typed manually into the paper.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence


DEFAULT_SOURCE_PATHS = {
    "lower": Path("artifacts/proof_audit/lower_corridor/lower_corridor_audit.json"),
    "upper": Path("artifacts/proof_audit/upper_obstruction/upper_obstruction_audit.json"),
    "transport": Path("artifacts/proof_audit/transport_budget/transport_budget_audit.json"),
    "domain": Path("artifacts/proof_audit/arithmetic_domain/arithmetic_domain_audit.json"),
    "gl2z": Path("artifacts/proof_audit/gl2z_normalization/gl2z_normalization_audit.json"),
    "replay": Path("artifacts/proof_audit/replay/replay_runtime_table.json"),
    "full_verified": Path("artifacts/proof_audit/replay/full_verified_report.json"),
}

EXPECTED_TABLES = {
    "lower_corridor_segments": Path("tables/proof_audit/lower_corridor_segments.tex"),
    "upper_obstruction_margin": Path("tables/proof_audit/upper_obstruction_margin.tex"),
    "transport_budget": Path("tables/proof_audit/transport_budget.tex"),
    "domain_grammar_counts": Path("tables/proof_audit/domain_grammar_counts.tex"),
    "replay_protocol": Path("tables/proof_audit/replay_protocol.tex"),
}

EXPECTED_FIGURES = {
    "lower_chain_margins": Path("figures/proof_audit/lower_chain_margins.pdf"),
    "upper_obstruction_margin_decomposition": Path("figures/proof_audit/upper_obstruction_margin_decomposition.pdf"),
    "transport_budget_waterfall": Path("figures/proof_audit/transport_budget_waterfall.pdf"),
    "arithmetic_domain_route_counts": Path("figures/proof_audit/arithmetic_domain_route_counts.pdf"),
    "replay_protocol_tiers": Path("figures/proof_audit/replay_protocol_tiers.pdf"),
}

MANIFEST_PATH = Path("artifacts/proof_audit/manuscript_outputs/manuscript_audit_outputs_manifest.json")


# ---------------------------------------------------------------------------
# Basic IO helpers
# ---------------------------------------------------------------------------


def read_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, sort_keys=True)
        f.write("\n")


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def ensure_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def as_float(value: Any, default: float = 0.0) -> float:
    try:
        if value is None:
            return default
        return float(value)
    except Exception:
        return default


def fmt_num(value: Any, digits: int = 4) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "--"
    try:
        x = float(value)
    except Exception:
        return str(value)
    if math.isnan(x):
        return "nan"
    if x == 0:
        return "0"
    ax = abs(x)
    if ax < 1e-3 or ax >= 1e4:
        return f"{x:.{digits}e}"
    return f"{x:.{digits}g}"


def latex_escape(s: Any) -> str:
    text = str(s)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(ch, ch) for ch in text)


# ---------------------------------------------------------------------------
# LaTeX table generation
# ---------------------------------------------------------------------------


def latex_tabular(headers: Sequence[str], rows: Sequence[Sequence[Any]], caption: str, label: str) -> str:
    alignment = "l" * len(headers)
    out = []
    out.append("% AUTO-GENERATED by scripts/generate_manuscript_audit_tables.py")
    out.append("% Source: proof-audit JSON/CSV payloads. Do not edit by hand.")
    out.append(r"\begin{table}[htbp]")
    out.append(r"\centering")
    out.append(r"\small")
    out.append(r"\begin{tabular}{" + alignment + r"}")
    out.append(r"\hline")
    out.append(" & ".join(latex_escape(h) for h in headers) + r" \\")
    out.append(r"\hline")
    for row in rows:
        out.append(" & ".join(latex_escape(cell) for cell in row) + r" \\")
    out.append(r"\hline")
    out.append(r"\end{tabular}")
    out.append(r"\caption{" + latex_escape(caption) + r"}")
    out.append(r"\label{" + latex_escape(label) + r"}")
    out.append(r"\end{table}")
    out.append("")
    return "\n".join(out)


def write_table(path: Path, headers: Sequence[str], rows: Sequence[Sequence[Any]], caption: str, label: str) -> None:
    ensure_parent(path)
    path.write_text(latex_tabular(headers, rows, caption, label), encoding="utf-8")


def build_lower_table(lower: Mapping[str, Any]) -> tuple[list[str], list[list[Any]], str, str]:
    rows: list[list[Any]] = []
    for seg in lower.get("segments", []):
        rows.append([
            seg.get("segment_id", ""),
            f"[{fmt_num(seg.get('K_lo'))}, {fmt_num(seg.get('K_hi'))}]",
            seg.get("N", ""),
            fmt_num(seg.get("radii_margin"), 5),
            fmt_num(seg.get("overlap_with_next"), 5),
            "yes" if seg.get("certified") else "no",
        ])
    rows.append([
        "final anchor",
        f"[{fmt_num(lower.get('final_anchor', [None, None])[0])}, {fmt_num(lower.get('final_anchor', [None, None])[1])}]",
        "--",
        "--",
        "--",
        "reached" if lower.get("final_anchor_reached") else "not reached",
    ])
    return ["segment", "$K$ interval", "$N$", "radii margin", "overlap", "status"], rows, (
        "Lower-corridor proof-audit segments. The final-anchor row is generated from the audit payload and "
        "records the current known lower gap rather than silently promoting the compact replay anchor."
    ), "tab:lower-corridor-audit-segments"


def build_upper_table(upper: Mapping[str, Any]) -> tuple[list[str], list[list[Any]], str, str]:
    ledger = upper.get("ledger", {})
    rows = [
        ["upper obstruction interval", f"[{fmt_num(ledger.get('upper_lo'))}, {fmt_num(ledger.get('upper_hi'))}]", "raw interval"],
        ["analytic barrier interval", f"[{fmt_num(ledger.get('barrier_lo'))}, {fmt_num(ledger.get('barrier_hi'))}]", "raw interval"],
        ["analytic incompatibility margin", fmt_num(upper.get("analytic_incompatibility_margin"), 6), "barrier lower minus upper ceiling"],
        ["upper localization width", fmt_num(ledger.get("upper_width"), 6), "interval width"],
        ["gap minus upper width", fmt_num(upper.get("gap_minus_upper_width"), 6), "derived margin"],
        ["gap/localization ratio", fmt_num(upper.get("gap_to_localization_ratio"), 6), "derived ratio"],
        ["tail denominators", ", ".join(str(x) for x in upper.get("tail_qs", [])), "tail coherence"],
        ["support fraction floor", fmt_num(upper.get("support_fraction_floor"), 4), "support geometry"],
        ["validator failures", len(upper.get("validator_failures", [])), "must be zero"],
    ]
    return ["quantity", "value", "proof role"], rows, (
        "Upper-obstruction margin ledger generated from the Phase-3 proof-audit JSON payload."
    ), "tab:upper-obstruction-margin-ledger"


def build_transport_table(transport: Mapping[str, Any]) -> tuple[list[str], list[list[Any]], str, str]:
    rows: list[list[Any]] = []
    for component in transport.get("components", []):
        rows.append([
            component.get("name", ""),
            fmt_num(component.get("value"), 6),
            component.get("formula", ""),
            ", ".join(component.get("source_fields", [])),
        ])
    rows.extend([
        ["total charged", fmt_num(transport.get("total_charged"), 6), "sum of components", "component ledger"],
        ["available gap", fmt_num(transport.get("available_gap"), 6), "comparison gap", "audit payload"],
        ["remaining margin", fmt_num(transport.get("remaining_margin"), 6), "available gap minus total charged", "derived inequality"],
        ["margin ratio", fmt_num(transport.get("margin_ratio"), 6), "available gap / total charged", "derived ratio"],
    ])
    return ["component", "bound", "formula", "source fields"], rows, (
        "Decomposed transport budget generated from the Phase-4 audit payload."
    ), "tab:transport-budget-audit"


def build_domain_table(domain: Mapping[str, Any]) -> tuple[list[str], list[list[Any]], str, str]:
    counts = domain.get("route_counts", {})
    route_order = ["screened", "ranked", "pruned", "lifecycle", "termination", "omitted", "uncontrolled"]
    rows = [[route, counts.get(f"{route}_count", counts.get(route, 0)), "generated route count"] for route in route_order]
    rows.extend([
        ["total generated", counts.get("generated_record_count", len(domain.get("records", []))), "all generated records"],
        ["failure fields empty", counts.get("failure_fields_empty", domain.get("failure_fields_empty")), "validator condition"],
        ["omitted-tail status", counts.get("omitted_tail_status", domain.get("omitted_tail_status")), "tail-control convention"],
    ])
    return ["route", "count/status", "role"], rows, (
        "Generated arithmetic-domain route counts. The table is generated directly from the Phase-5 domain audit."
    ), "tab:domain-grammar-route-counts"


def build_replay_table(replay: Mapping[str, Any], full_verified: Mapping[str, Any] | None = None) -> tuple[list[str], list[list[Any]], str, str]:
    order = ["minimal", "downstream", "artifact_audit_suite", "heavy_lower", "heavy_upper", "full_verified"]
    rows: list[list[Any]] = []
    for key in order:
        entry = replay.get(key, {})
        rows.append([
            key,
            entry.get("script", ""),
            "yes" if entry.get("heavy_layer") else "no",
            fmt_num(entry.get("runtime_seconds"), 4),
            entry.get("returncode", "not run"),
        ])
    if full_verified:
        rows.append([
            "strict final ready",
            "scripts/replay_full_verified.py",
            "summary",
            fmt_num(full_verified.get("runtime_seconds"), 4),
            full_verified.get("status", ""),
        ])
    return ["tier", "script", "heavy layer", "runtime sec.", "status/returncode"], rows, (
        "Replay protocol tiers and runtime/status fields generated from the Phase-7 replay audit payload."
    ), "tab:replay-protocol-tiers"


# ---------------------------------------------------------------------------
# Tiny vector-PDF backend
# ---------------------------------------------------------------------------


def _pdf_escape_text(text: Any) -> str:
    s = str(text)
    return s.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


@dataclass
class MiniPDF:
    width: int = 612
    height: int = 792
    content: list[str] | None = None

    def __post_init__(self) -> None:
        if self.content is None:
            self.content = []

    def line(self, x1: float, y1: float, x2: float, y2: float, width: float = 1.0) -> None:
        self.content.append(f"{width:.3f} w {x1:.3f} {y1:.3f} m {x2:.3f} {y2:.3f} l S")

    def rect(self, x: float, y: float, w: float, h: float, gray: float = 0.85, stroke: bool = False) -> None:
        gray = max(0.0, min(1.0, gray))
        op = "B" if stroke else "f"
        self.content.append(f"{gray:.3f} g {x:.3f} {y:.3f} {w:.3f} {h:.3f} re {op} 0 g")

    def text(self, x: float, y: float, text: Any, size: int = 9, align: str = "left") -> None:
        escaped = _pdf_escape_text(text)
        # Approximate centering/right alignment using glyph-count width.
        adj = 0.0
        if align == "center":
            adj = -0.5 * len(str(text)) * size * 0.48
        elif align == "right":
            adj = -len(str(text)) * size * 0.48
        self.content.append(f"BT /F1 {size} Tf {x + adj:.3f} {y:.3f} Td ({escaped}) Tj ET")

    def write(self, path: Path) -> None:
        ensure_parent(path)
        stream = "\n".join(self.content or []) + "\n"
        objs: list[bytes] = []
        objs.append(b"<< /Type /Catalog /Pages 2 0 R >>")
        objs.append(b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>")
        page = f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {self.width} {self.height}] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>".encode()
        objs.append(page)
        objs.append(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
        stream_b = stream.encode("latin-1", errors="replace")
        objs.append(b"<< /Length " + str(len(stream_b)).encode() + b" >>\nstream\n" + stream_b + b"endstream")
        pdf = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
        offsets = [0]
        for i, obj in enumerate(objs, 1):
            offsets.append(len(pdf))
            pdf += f"{i} 0 obj\n".encode() + obj + b"\nendobj\n"
        xref_pos = len(pdf)
        pdf += f"xref\n0 {len(objs)+1}\n".encode()
        pdf += b"0000000000 65535 f \n"
        for off in offsets[1:]:
            pdf += f"{off:010d} 00000 n \n".encode()
        pdf += f"trailer << /Size {len(objs)+1} /Root 1 0 R >>\nstartxref\n{xref_pos}\n%%EOF\n".encode()
        path.write_bytes(bytes(pdf))


def draw_bar_chart(path: Path, title: str, labels: Sequence[str], values: Sequence[float], *, subtitle: str = "", y_label: str = "", value_format: str = "{:.2e}") -> None:
    pdf = MiniPDF()
    left, bottom, width, height = 78, 155, 455, 420
    values = [float(v) for v in values]
    max_val = max([abs(v) for v in values] + [1.0])
    if max_val <= 0:
        max_val = 1.0
    pdf.text(306, 742, title, size=15, align="center")
    if subtitle:
        pdf.text(306, 722, subtitle, size=9, align="center")
    pdf.line(left, bottom, left, bottom + height, 0.8)
    pdf.line(left, bottom, left + width, bottom, 0.8)
    for i in range(6):
        y = bottom + height * i / 5
        pdf.line(left - 4, y, left + width, y, 0.25)
        pdf.text(left - 8, y - 3, value_format.format(max_val * i / 5), size=7, align="right")
    n = max(1, len(values))
    slot = width / n
    bar_w = min(46, slot * 0.62)
    for i, (label, val) in enumerate(zip(labels, values)):
        x = left + slot * i + (slot - bar_w) / 2
        h = 0 if max_val == 0 else height * max(0, val) / max_val
        gray = 0.82 - 0.18 * (i % 3) / 2
        pdf.rect(x, bottom, bar_w, h, gray=gray, stroke=True)
        pdf.text(x + bar_w / 2, bottom + h + 9, value_format.format(val), size=7, align="center")
        short_label = str(label)
        if len(short_label) > 20:
            short_label = short_label[:17] + "..."
        pdf.text(x + bar_w / 2, bottom - 20, short_label, size=7, align="center")
    if y_label:
        pdf.text(35, bottom + height / 2, y_label, size=8, align="center")
    pdf.text(306, 92, "Generated from proof-audit JSON/CSV payloads; not manually typed.", size=8, align="center")
    pdf.write(path)


def draw_waterfall(path: Path, title: str, components: Sequence[tuple[str, float]], available_gap: float, remaining_margin: float) -> None:
    labels = [name for name, _ in components] + ["remaining"]
    values = [value for _, value in components] + [remaining_margin]
    pdf = MiniPDF()
    left, bottom, width, height = 78, 150, 455, 420
    max_val = max(available_gap, sum(max(0, v) for v in values), 1e-12)
    pdf.text(306, 742, title, size=15, align="center")
    pdf.text(306, 722, f"available gap = {available_gap:.3e}; remaining margin = {remaining_margin:.3e}", size=9, align="center")
    pdf.line(left, bottom, left, bottom + height, 0.8)
    pdf.line(left, bottom, left + width, bottom, 0.8)
    pdf.line(left, bottom + height * available_gap / max_val, left + width, bottom + height * available_gap / max_val, 1.2)
    pdf.text(left + width + 8, bottom + height * available_gap / max_val - 3, "available", size=8)
    n = max(1, len(values))
    slot = width / n
    bar_w = min(45, slot * 0.58)
    for i, (label, val) in enumerate(zip(labels, values)):
        x = left + slot * i + (slot - bar_w) / 2
        h = height * max(0, val) / max_val
        pdf.rect(x, bottom, bar_w, h, gray=0.78 if label != "remaining" else 0.62, stroke=True)
        pdf.text(x + bar_w / 2, bottom + h + 9, f"{val:.2e}", size=7, align="center")
        pdf.text(x + bar_w / 2, bottom - 20, label, size=7, align="center")
    pdf.text(306, 92, "Transport pass condition: available gap exceeds the total charged budget.", size=8, align="center")
    pdf.write(path)


def draw_protocol_tiers(path: Path, replay: Mapping[str, Any], full_verified: Mapping[str, Any] | None) -> None:
    order = ["minimal", "downstream", "artifact_audit_suite", "heavy_lower", "heavy_upper", "full_verified"]
    pdf = MiniPDF()
    pdf.text(306, 742, "Replay protocol tiers", size=15, align="center")
    status = full_verified.get("status") if full_verified else "unknown"
    strict = full_verified.get("strict_final_ready") if full_verified else False
    pdf.text(306, 722, f"full verified status: {status}; strict_final_ready={strict}", size=9, align="center")
    x0, y0 = 75, 590
    box_w, box_h, gap = 160, 56, 24
    for i, key in enumerate(order):
        row = i // 3
        col = i % 3
        x = x0 + col * (box_w + gap)
        y = y0 - row * 145
        entry = replay.get(key, {})
        gray = 0.70 if entry.get("heavy_layer") else 0.88
        pdf.rect(x, y, box_w, box_h, gray=gray, stroke=True)
        pdf.text(x + box_w / 2, y + 35, key, size=10, align="center")
        runtime = entry.get("runtime_seconds", 0)
        pdf.text(x + box_w / 2, y + 18, f"runtime {fmt_num(runtime, 3)} sec", size=7, align="center")
        pdf.text(x + box_w / 2, y + 6, "heavy" if entry.get("heavy_layer") else "lightweight", size=7, align="center")
        if i < len(order) - 1 and col != 2:
            pdf.line(x + box_w, y + box_h / 2, x + box_w + gap, y + box_h / 2, 0.8)
    pdf.text(306, 250, "Known lower-anchor gap is preserved as a fail-closed strict-readiness blocker.", size=8, align="center")
    pdf.write(path)


# ---------------------------------------------------------------------------
# Public generation functions
# ---------------------------------------------------------------------------


def load_sources(root: Path = Path(".")) -> dict[str, Any]:
    sources: dict[str, Any] = {}
    missing = []
    for key, rel in DEFAULT_SOURCE_PATHS.items():
        path = root / rel
        if not path.exists():
            missing.append(str(rel))
        else:
            sources[key] = read_json(path)
    if missing:
        raise FileNotFoundError("Missing proof-audit source payloads: " + "; ".join(missing))
    return sources


def generate_manuscript_tables(root: Path = Path(".")) -> dict[str, Any]:
    sources = load_sources(root)
    table_specs = {
        "lower_corridor_segments": build_lower_table(sources["lower"]),
        "upper_obstruction_margin": build_upper_table(sources["upper"]),
        "transport_budget": build_transport_table(sources["transport"]),
        "domain_grammar_counts": build_domain_table(sources["domain"]),
        "replay_protocol": build_replay_table(sources["replay"], sources["full_verified"]),
    }
    outputs = []
    for key, spec in table_specs.items():
        path = root / EXPECTED_TABLES[key]
        write_table(path, *spec)
        outputs.append(path)
    return build_manifest(root, table_outputs=outputs, figure_outputs=[])


def generate_manuscript_figures(root: Path = Path(".")) -> dict[str, Any]:
    sources = load_sources(root)

    lower = sources["lower"]
    segs = lower.get("segments", [])
    draw_bar_chart(
        root / EXPECTED_FIGURES["lower_chain_margins"],
        "Lower-corridor radii margins",
        [seg.get("segment_id", f"seg{i}") for i, seg in enumerate(segs)],
        [as_float(seg.get("radii_margin")) for seg in segs],
        subtitle=f"status={lower.get('status')}; final_anchor_reached={lower.get('final_anchor_reached')}",
        y_label="margin",
        value_format="{:.1e}",
    )

    upper = sources["upper"]
    ledger = upper.get("ledger", {})
    draw_bar_chart(
        root / EXPECTED_FIGURES["upper_obstruction_margin_decomposition"],
        "Upper-obstruction margin decomposition",
        ["incompatibility", "gap-width", "upper width", "barrier width"],
        [
            as_float(upper.get("analytic_incompatibility_margin")),
            as_float(upper.get("gap_minus_upper_width")),
            as_float(ledger.get("upper_width")),
            as_float(ledger.get("barrier_width")),
        ],
        subtitle=f"status={upper.get('status')}; validator failures={len(upper.get('validator_failures', []))}",
        y_label="margin/width",
        value_format="{:.2e}",
    )

    transport = sources["transport"]
    draw_waterfall(
        root / EXPECTED_FIGURES["transport_budget_waterfall"],
        "Transport budget waterfall",
        [(c.get("name", "component"), as_float(c.get("value"))) for c in transport.get("components", [])],
        as_float(transport.get("available_gap")),
        as_float(transport.get("remaining_margin")),
    )

    domain = sources["domain"]
    counts = domain.get("route_counts", {})
    route_labels = ["screened", "ranked", "pruned", "lifecycle", "termination", "omitted", "uncontrolled"]
    draw_bar_chart(
        root / EXPECTED_FIGURES["arithmetic_domain_route_counts"],
        "Arithmetic-domain generated route counts",
        route_labels,
        [as_float(counts.get(f"{name}_count", counts.get(name, 0))) for name in route_labels],
        subtitle=f"generated records={counts.get('generated_record_count', len(domain.get('records', [])))}; status={domain.get('status')}",
        y_label="count",
        value_format="{:.0f}",
    )

    draw_protocol_tiers(root / EXPECTED_FIGURES["replay_protocol_tiers"], sources["replay"], sources["full_verified"])

    outputs = [root / p for p in EXPECTED_FIGURES.values()]
    return build_manifest(root, table_outputs=[], figure_outputs=outputs)


def build_manifest(root: Path, table_outputs: Sequence[Path] | None = None, figure_outputs: Sequence[Path] | None = None) -> dict[str, Any]:
    table_outputs = list(table_outputs or [])
    figure_outputs = list(figure_outputs or [])
    source_entries = []
    for key, rel in DEFAULT_SOURCE_PATHS.items():
        path = root / rel
        if path.exists():
            source_entries.append({"key": key, "path": str(rel), "sha256": sha256_file(path), "bytes": path.stat().st_size})
    output_paths = list(table_outputs) + list(figure_outputs)
    output_entries = []
    for path in output_paths:
        if path.exists():
            output_entries.append({"path": str(path.relative_to(root)), "sha256": sha256_file(path), "bytes": path.stat().st_size})
    # If a manifest already exists, merge outputs so table-only and figure-only runs accumulate.
    manifest_file = root / MANIFEST_PATH
    existing_outputs: dict[str, dict[str, Any]] = {}
    if manifest_file.exists():
        try:
            old = read_json(manifest_file)
            for entry in old.get("outputs", []):
                existing_outputs[entry.get("path", "")] = entry
        except Exception:
            pass
    for entry in output_entries:
        existing_outputs[entry["path"]] = entry
    lower_status = None
    known_lower_gap = None
    try:
        lower = read_json(root / DEFAULT_SOURCE_PATHS["lower"])
        lower_status = lower.get("status")
        known_lower_gap = not bool(lower.get("final_anchor_reached"))
    except Exception:
        pass
    manifest = {
        "schema": "phase10_manuscript_audit_outputs_v1",
        "status": "passed-with-known-lower-gap" if known_lower_gap else "passed",
        "known_lower_gap": bool(known_lower_gap),
        "lower_status": lower_status,
        "source_payloads": source_entries,
        "outputs": [existing_outputs[k] for k in sorted(existing_outputs)],
        "expected_tables": {k: str(v) for k, v in EXPECTED_TABLES.items()},
        "expected_figures": {k: str(v) for k, v in EXPECTED_FIGURES.items()},
        "manual_editing_allowed": False,
        "generation_principle": "All manuscript tables and figures are generated directly from proof-audit JSON/CSV payloads.",
    }
    write_json(manifest_file, manifest)
    return manifest


def generate_all_manuscript_outputs(root: Path = Path(".")) -> dict[str, Any]:
    generate_manuscript_tables(root)
    generate_manuscript_figures(root)
    return build_manifest(root, [root / p for p in EXPECTED_TABLES.values()], [root / p for p in EXPECTED_FIGURES.values()])


def cli_tables(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate manuscript audit LaTeX tables from proof-audit JSON payloads.")
    parser.add_argument("--root", default=".", help="Repository root")
    parser.add_argument("--strict", action="store_true", help="Fail if any expected table is missing after generation")
    args = parser.parse_args(argv)
    root = Path(args.root)
    manifest = generate_manuscript_tables(root)
    missing = [str(p) for p in EXPECTED_TABLES.values() if not (root / p).exists()]
    if args.strict and missing:
        raise SystemExit("Missing expected tables: " + "; ".join(missing))
    print(json.dumps({"status": manifest["status"], "generated_tables": len(EXPECTED_TABLES), "missing": missing}, indent=2))
    return 0 if not missing else 1


def cli_figures(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate manuscript audit PDF figures from proof-audit JSON payloads.")
    parser.add_argument("--root", default=".", help="Repository root")
    parser.add_argument("--strict", action="store_true", help="Fail if any expected figure is missing after generation")
    args = parser.parse_args(argv)
    root = Path(args.root)
    manifest = generate_manuscript_figures(root)
    missing = [str(p) for p in EXPECTED_FIGURES.values() if not (root / p).exists()]
    if args.strict and missing:
        raise SystemExit("Missing expected figures: " + "; ".join(missing))
    print(json.dumps({"status": manifest["status"], "generated_figures": len(EXPECTED_FIGURES), "missing": missing}, indent=2))
    return 0 if not missing else 1


def cli_all(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate all Phase-10 manuscript audit tables and figures.")
    parser.add_argument("--root", default=".", help="Repository root")
    parser.add_argument("--strict", action="store_true", help="Fail if any expected output is missing")
    args = parser.parse_args(argv)
    root = Path(args.root)
    manifest = generate_all_manuscript_outputs(root)
    missing = [str(p) for p in list(EXPECTED_TABLES.values()) + list(EXPECTED_FIGURES.values()) if not (root / p).exists()]
    if args.strict and missing:
        raise SystemExit("Missing expected manuscript outputs: " + "; ".join(missing))
    print(json.dumps({"status": manifest["status"], "known_lower_gap": manifest["known_lower_gap"], "outputs": len(manifest["outputs"]), "missing": missing}, indent=2))
    return 0 if not missing else 1
